### ISSUE TITLE
Update the dependencies 

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/Patent-Blockchain#8]

**Comment by KKghub** [comment]
If I am not mistaken, the ask here is to perform `npm update` on the repository?

**Comment by JithinAntony4** [comment]
@Ishaan28malik can I do this?

**Comment by LuizHAP** [comment]
Hello, I'm already checking your project

**Comment by LuizHAP** [comment]
Hello, could you just validate the PR, please, and check your repository, as it is pointing to me as unreadable for Hacktoberfest

![image](https://user-images.githubusercontent.com/20971507/94993494-d6e47980-0567-11eb-8b3d-2199eec11fb6.png)

**Comment by LuizHAP** [comment]
@Ishaan28malik just need to change the topics from Hacktoberfest (https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by Ishaan28malik** [comment]
> @Ishaan28malik can I do this?

Sure

**Comment by Ishaan28malik** [comment]
> Hello, could you just validate the PR, please, and check your repository, as it is pointing to me as unreadable for Hacktoberfest
> 
> ![image](https://user-images.githubusercontent.com/20971507/94993494-d6e47980-0567-11eb-8b3d-2199eec11fb6.png)

I just made an update.

**Comment by Ishaan28malik** [comment]
@LuizHAP there are still dependencies that need updates.
can you resolve that ?

**Comment by geetu-sharma** [comment]
@Ishaan28malik I want to work on this

**Comment by Ishaan28malik** [comment]
@geetu-sharma sure.
